set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

default:
  @just --list

run run_id='' extra_env='':
  ~/miniconda3/bin/python ./launcher.py run --run-id "{{run_id}}" --extra-env "{{extra_env}}"

smoke run_id='' extra_env='':
  ~/miniconda3/bin/python ./launcher.py smoke --run-id "{{run_id}}" --extra-env "{{extra_env}}"

record run_id='' extra_env='':
  ~/miniconda3/bin/python ./launcher.py record --run-id "{{run_id}}" --extra-env "{{extra_env}}"

status pod_id='':
  if [[ -n "{{pod_id}}" ]]; then ~/miniconda3/bin/python ./launcher.py status --pod-id "{{pod_id}}"; else ~/miniconda3/bin/python ./launcher.py status; fi

ssh pod_id='':
  if [[ -n "{{pod_id}}" ]]; then ~/miniconda3/bin/python ./launcher.py ssh --pod-id "{{pod_id}}"; else ~/miniconda3/bin/python ./launcher.py ssh; fi

stop pod_id='':
  if [[ -n "{{pod_id}}" ]]; then ~/miniconda3/bin/python ./launcher.py stop --pod-id "{{pod_id}}"; else ~/miniconda3/bin/python ./launcher.py stop; fi

delete pod_id='':
  if [[ -n "{{pod_id}}" ]]; then ~/miniconda3/bin/python ./launcher.py delete --pod-id "{{pod_id}}"; else ~/miniconda3/bin/python ./launcher.py delete; fi

summarize runs_dir="/workspace/parameter-golf/logs/record_runs":
  ~/miniconda3/bin/python ./launcher.py summarize --runs-dir "{{runs_dir}}"
