set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

default:
  @just --list

run run_id='' extra_env='':
  ~/miniconda3/bin/python ./launcher.py run --run-id "{{run_id}}" --extra-env "{{extra_env}}"

smoke run_id='' extra_env='':
  ~/miniconda3/bin/python ./launcher.py smoke --run-id "{{run_id}}" --extra-env "{{extra_env}}"

record run_id='' extra_env='':
  ~/miniconda3/bin/python ./launcher.py record --run-id "{{run_id}}" --extra-env "{{extra_env}}"

status:
  ~/miniconda3/bin/python ./launcher.py status

ssh:
  ~/miniconda3/bin/python ./launcher.py ssh

stop:
  ~/miniconda3/bin/python ./launcher.py stop

delete:
  ~/miniconda3/bin/python ./launcher.py delete

summarize runs_dir="/workspace/parameter-golf/logs/record_runs":
  ~/miniconda3/bin/python ./launcher.py summarize --runs-dir "{{runs_dir}}"
